trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    mkidr build && cd build && cmake ..
  displayName: 'Configuring CMake'